Running 1 test case...
test.cpp(18): error: in "test_collections_vectors": check a == b has failed. 
Mismatch at position 1: 2 != 5. 
test.cpp(22): error: in "test_collections_vectors": check b >= c has failed. 
Second collection has extra trailing elements.

*** 2 failures are detected in the test module "boost_test_sequence"
