//[example_output
> decorator_20
Running 2 test cases...
decorator_20.cpp(28): error: in "suite1/test_2": check 2 != 2 has failed [2 == 2]
decorator_20.cpp(34): error: in "suite1/test_io": check 3 != 3 has failed [3 == 3]

*** 2 failures are detected in the test module "decorator_20"


> decorator_20 --list_content
suite1*[0]
    test_1 [0]
    test_2*[0]
    test_io*[0]
    test_db [0]
//]
