//[example_output
> example
Running 1 test case...
test.cpp(14): error: in "test_case1": check false has failed
Failure occurred in a following context:
    Gamma
    Delta

*** 1 failure detected in test module "example"

//]