//[example_output
> example
Running 1 test case...
test.cpp(12): error: in "test_case1": check false has failed

*** 1 failure detected in test module "example"
//]