//[example_output
> example
Running 3 test cases...
test.cpp(24): error: in "test_case3": check false has failed

*** 1 failure detected in test module "example"

> example --list_content
test_case1
test_case3
test_case4
//]