//[example_output
> tolerance_03
Running 2 test cases...
test.cpp(18): error: in "failing": check x - d < x has failed [10 - 1.0000000000000001e-005 >= 10]. Relative difference is within tolerance [1e-006 < 0.001]
test.cpp(19): error: in "failing": check x - d != x has failed [10 - 1.0000000000000001e-005 == 10]. Relative difference is within tolerance [1e-006 < 0.001]
test.cpp(21): error: in "failing": check d > .0 has failed [1.0000000000000001e-005 <= 0]. Absolute value is within tolerance [|1e-005| < 0.001]
test.cpp(22): error: in "failing": check d < .0 has failed [1.0000000000000001e-005 >= 0]

*** 4 failures are detected in the test module "tolerance_03"
//]